name: pages

on:
  push:
    branches: [ main ]

jobs:
  pages:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
        
      - name: deploy-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: slides
